[package]
name = "textplots"
description = "Terminal plotting library."
version = "0.5.4"
authors = ["Alexey Suslov <alexey.suslov@gmail.com>"]
license = "MIT"
repository = "https://github.com/loony-bean/textplots-rs"
keywords = ["plotting", "unicode", "charts"]
categories = ["visualization"]
readme = "README.md"

[badges]
travis-ci = { repository = "loony-bean/textplots-rs", branch = "master" }

[dependencies]
drawille = "0.2.3"
