[package]
name = "textplots"
description = "Terminal plotting library."
version = "0.1.0"
authors = ["Alexey Suslov <alexey.suslov@gmail.com>"]
license = "MIT"
repository = "https://github.com/loony-bean/textplots-rs"
keywords = ["plotting", "ascii", "unicode", "charts"]
categories = ["command-line-utilities", "visualization"]

[badges]
travis-ci = { repository = "loony-bean/textplots-rs", branch = "master" }

[dependencies]
drawille = "0.2.3"
